### ISSUE TITLE
Variants need to be supported

### ISSUE THREAD

**Issue by ToxicBakery** [ToxicBakery/BettererNaming#1]
Instead of dumb tacking to the default assembleRelease task, just tack onto variants and inspect their build types directly.

```
if (hasApp) {
   variants = project.android.applicationVariants
} else {
   variants = project.android.libraryVariants
}


variants.all { variant ->
   if (!variant.buildType.isDebuggable()) {
      return;
   }

   // Do work..
}
```

**Comment by alorma** [comment]
Any news on this issue? I really need that :P

**Comment by ToxicBakery** [comment]
Sometime this month it will become priority. I'm in a cycle of prototyping at work right now so production related work is at the bottom of the totem.
